export const INITIAL_TODO_LIST = 'initial_todo_list'
export const GET_INIT_LIST = 'get_init_list'
export const CHANGE_INPUT_VALUE = 'change_input_value';
export const ADD_TODO_ITEM = 'add_todo_item';
export const DELETE_TODO_ITEM = 'delete_todo_item';
export const SEARCH_FOCUS = 'search_focus' ;
export const SEARCH_BLUR = 'search_blur';
export const CHANGE_LIST = 'change_list';
export const MOUSE_ENTER = 'mouse_enter';
export const MOUSE_LEAVE = 'mouse_leave';
export const CHANGE_PAGE = 'change_page';